### PR TITLE
fix progress percent calculation and print issue in interactive mode 

### PR DESCRIPTION
**Pull request by jaysim**
Fix print "y/N" without any message in interactive mode. It's regression of 85f9a40
Fix progress percent calculation bug in -n option.
Modify README.md

### CODE REVIEW

**Comment by namjaejeon** [comment]
applied them to #master!

**Comment by namjaejeon** [comment]
Applied the recent patches you have added to this PR.
Thanks!

**Comment by namjaejeon** [comment]
Applied 3 patches to master, Thanks!

**Comment by namjaejeon** [comment]
Problem is stiil happening on two tests.

generic/312 1s ... _check_generic_filesystem: filesystem on /dev/sdc2 is inconsistent
(see /home/linkinjeon/tests/xfstests-ntfs/results//generic/312.full for details)

generic/483       _check_generic_filesystem: filesystem on /dev/sdc2 is inconsistent
(see /home/linkinjeon/tests/xfstests-ntfs/results//generic/483.full for details)

**Comment by jaysim** [comment]
> Problem is stiil happening on two tests.
> 
> generic/312 1s ... _check_generic_filesystem: filesystem on /dev/sdc2 is inconsistent (see /home/linkinjeon/tests/xfstests-ntfs/results//generic/312.full for details)
> 
> generic/483 _check_generic_filesystem: filesystem on /dev/sdc2 is inconsistent (see /home/linkinjeon/tests/xfstests-ntfs/results//generic/483.full for details)

generic/312 issue is resolved with new [2ade2ac](https://github.com/ntfsprogs-plus/ntfsprogs-plus/pull/25/commits/2ade2acba424cb23a366ad04aafb1d8d0fd125cd) patch
but I think generic/483 should be checked first about different allocated size
`Allocated size is different (IDX/$FN:2048000 MFT/$DATA:1310720) on inode(28, bar). Fix it. (y/N)? N`
`Allocated size is different (IDX/$FN:1048576 MFT/$DATA:3145728) on inode(29, baz). Fix it. (y/N)? N`
`Allocated size is different (IDX/$FN:262144 MFT/$DATA:1310720) on inode(27, foo). Fix it. (y/N)? N`

**Comment by namjaejeon** [comment]
Please check this warning.

```
In function ‘ntfsck_update_runlist’,
    inlined from ‘ntfsck_check_non_resident_attr’ at ntfsck.c:2354:8,
    inlined from ‘ntfsck_check_inode_non_resident’ at ntfsck.c:2674:9:
ntfsck.c:2285:18: warning: ‘backup_attr_list_size’ may be used uninitialized [-Wmaybe-uninitialized]
 2285 |         if (actx && ni->attr_list_size != backup_attr_list_size) {
      |             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ntfsck.c: In function ‘ntfsck_check_inode_non_resident’:
ntfsck.c:2264:13: note: ‘backup_attr_list_size’ was declared here
 2264 |         u32 backup_attr_list_size;
      |             ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by jaysim** [comment]
> Please check this warning.
> 
> ```
> In function ‘ntfsck_update_runlist’,
>     inlined from ‘ntfsck_check_non_resident_attr’ at ntfsck.c:2354:8,
>     inlined from ‘ntfsck_check_inode_non_resident’ at ntfsck.c:2674:9:
> ntfsck.c:2285:18: warning: ‘backup_attr_list_size’ may be used uninitialized [-Wmaybe-uninitialized]
>  2285 |         if (actx && ni->attr_list_size != backup_attr_list_size) {
>       |             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ntfsck.c: In function ‘ntfsck_check_inode_non_resident’:
> ntfsck.c:2264:13: note: ‘backup_attr_list_size’ was declared here
>  2264 |         u32 backup_attr_list_size;
>       |             ^~~~~~~~~~~~~~~~~~~~~
> ```

I fixed this issue and some static analyzation issues using cppcheck.
https://github.com/ntfsprogs-plus/ntfsprogs-plus/pull/25/commits/47a526796696af6712f1936bb43f83d20a31cc8d

**Comment by namjaejeon** [comment]
Applied, Thanks!

**Pull request closed without merging**
